# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:       pretty
# Setup
title:            Aaron Fraser
#tagline:          'Topics of Systems and Automation'
description:      'Thoughts of a Systems Engineer'
url:              http://afraser.io
#url:		  http://localhost
author:
  name:           'Aaron Fraser'
  url:            https://twitter.com/aaronmfraser

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/aaronmfraser/afraser.io

exclude: ["vendor"]
